name: tra
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.8.1

dependencies:
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.1
  http: ^1.4.0
  loader_overlay: ^5.0.0
  material_symbols_icons: ^4.2873.0
  modern_dialog: ^1.3.0
  shared_preferences: ^2.5.3
  stacked: ^3.5.0
  stacked_services: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
